### ISSUE TITLE
two bugs

### ISSUE THREAD

**Issue by db300** [genedelisa/TreeControl#1]
first:
file: FileSystemItem.swift
line: 79
error: stringByAppendingPathComponent is unavailable: Use URLByAppendingPathComponent on NSURL instead.

second:
same file
line: 143
error: lastPathComponent is unavailable: Use lastPathComponent on NSURL instead.

**Comment by genedelisa** [comment]
Not really a "bug"; it worked when published.
Swift 2 changed some syntax.
Updated.

**Comment by db300** [comment]
Well done.
It works.
